### ISSUE TITLE
Azure functions support

### ISSUE THREAD

**Issue by vl4d4** [awslabs/aws-dotnet-messaging#139]
### Describe the issue

I know that Azure functions don't have triggers/binding available for AWS resources like Logic Apps do, but since this is a .NET package can we say it somewhere in the docs that this package supports console app, worker/hosted service, ASP.NET API, AWS Lambda projects (not Azure functions).

### Links

[Blog](https://aws.amazon.com/blogs/developer/introducing-the-aws-message-processing-framework-for-net-preview/)

[Docs](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/msg-proc-fw.html)

**Comment by ashishdhingra** [comment]
@vl4d4 Good morning. Could you please clarify what needs to be updated in documentation? Are you looking for specific Azure function integration or what scenario is not working at your end?

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Closing due to lack of traction.
