### ISSUE TITLE
Question: Is it possible to use the scoped services within a message poller ?

### ISSUE THREAD

**Issue by madhub** [awslabs/aws-dotnet-messaging#46]
For ASP.NET core REST API , we have way to inject **scoped dependencies** , its good to provide similar capability for message poller.
Something similar to [Use scoped services within a BackgroundService](https://learn.microsoft.com/en-us/dotnet/core/extensions/scoped-service). Scope can be individual message pulled from queue or a group of message pulled.

**Comment by normj** [comment]
Excellent point, we should create a scope message handler invocation.

**Comment by ericsampson** [comment]
was this resolved by the linked PR?

**Comment by madhub** [comment]
> was this resolved by the linked PR?

Yes, resolved, closing the issue now
