### ISSUE TITLE
Change request to enable configure fatal error codes

### ISSUE THREAD

**Issue by ArchanaNeog** [awslabs/aws-dotnet-messaging#53]
I tried this messaging framework for one of our use cases and there are a few observations/suggestions from my end.

- Can we have configurable error codes that should be treated as fatal to stop the poller? 

Currently, the framework considers "InvalidAddress" and "AccessDenied" as fatal error codes which are declared as constant in the framework. 
 
`private static readonly HashSet<string> _fatalSQSErrorCodes = new HashSet<string>
    {
        "InvalidAddress",   // Returned for an invalid queue URL
        "AccessDenied"      // Returned with insufficient IAM permissions to read from the configured queue
    };`
	
As a consumer of this framework, I might want to set a few more error codes as fatal. 

- I Could not find the NuGet package AWS.Messaging. Am I missing something?

**Comment by ashovlin** [comment]
Now that the linked PR has been merged, this is possible when configured the SQS poller
```
  services.AddAWSMessageBus(builder =>
  {
      builder.AddSQSPoller("https://sqs.us-west-2.amazonaws.com/012345678910/MPF", options =>
      {
          options.IsSQSExceptionFatal = (exception) =>
          {
              // Here one can inspect the type and properties of the exception
              // to determine their own logic for when to stop the poller
              if (exception.ErrorCode == "InvalidAddress")
                  return true;
              return false;
          };
      });
  })
```
