### ISSUE TITLE
publish prerelease version on Nuget?

### ISSUE THREAD

**Issue by ericsampson** [awslabs/aws-dotnet-messaging#58]
Hi, the README currently has instructions to install the package, but it doesn't appear that it's available on Nuget (I'm guessing that it may be published to an internal AWS package server, hence why the readme instructions would make sense to y'all).

Would it be possible to publish a prerelease-flagged version of the package to Nuget?

Or if not, revise the readme so that the install instructions aren't misleading for non-AWS folks.

Thanks, this seems like an awesome project!!

**Comment by ashovlin** [comment]
Thanks for the interest! We're developing this in the open, but still have some milestones to go before we hit "Developer Preview" from the [AWS SDKs and Tools lifecycle](https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html). At that point we'll push the initial package to NuGet.

We still have some work to do focusing on FIFO support, telemetry, and performance hardening. Importantly we'll also take it through our internal security and open source review processes before publishing the initial NuGet package.

I agree the README can be misleading, we'll update that until the package is available publicly.

**Comment by ericsampson** [comment]
sounds good!

Does that mean that FIFO SQS isn't supported yet? I was expecting that all I'd have to do is use the correct FIFO queue name/arn.

Cheers

**Comment by normj** [comment]
@ericsampson You are correct from publishing side you can send a message to a FIFO queue by injecting the `ISQSPublisher` and using the `SQSOptions` on the publish method to include the group id. The main work we still need to do for FIFO is on the consumer side where if we receive a batch of messages from a FIFO queue to be sure to parallelize processing for messages with different group ids but serialize messages with the same group id.

**Comment by ericsampson** [comment]
closing as answered, the readme update will be done separately.

**Comment by ashovlin** [comment]
We've just published the initial beta packages on 2023-12-08:
* https://www.nuget.org/packages/AWS.Messaging
* https://www.nuget.org/packages/AWS.Messaging.Lambda
* https://www.nuget.org/packages/AWS.Messaging.Telemetry.OpenTelemetry
