### ISSUE TITLE
Document transport schema

### ISSUE THREAD

**Issue by ericsampson** [awslabs/aws-dotnet-messaging#60]
I'd like to consume my published messages using a Javascript lambda, so it would be great if the current message schema was documented somewhere obvious.

**Comment by ashovlin** [comment]
We're still building out the handwritten developer guide, and I imagine that eventually we can have a dedicated page for the schema. We do have it in the two locations below for now:
* [Message Format section in the Design Doc](https://github.com/awslabs/aws-dotnet-messaging/blob/main/docs/docs/design/message-processing-framework-design.md#message-format)
* [Customization section on the Getting Started page](https://awslabs.github.io/aws-dotnet-messaging/docs/getting-started.html#customization)

**Comment by ashovlin** [comment]
We also have it in the developer guide now at: https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/msg-proc-fw-customize.html

Resolving, but let us know if you're still looking for more info.
