### ISSUE TITLE
Consider making publishing examples more explicit re multiple message types

### ISSUE THREAD

**Issue by ericsampson** [awslabs/aws-dotnet-messaging#61]
It sounds dumb, but I didn't immediately realize from the readme and current example projects that `PublishAsync` is generic over the message type.

It could maybe help in the readme etc if the generic was explicitly specified even though it's not necessary for compilation, just to make this obvious to someone brand-new to the library.

Also consider tweaking the readme/projects so that they show publishing and consuming multiple message types

**Comment by ashovlin** [comment]
We've improved the XML documentation and samples in release 0.2.0-beta via #100. Let us know if we can still clarify anything.
